Work on bug-3, add hover and made featureBox links
matwjablonski/wdp-2312-01 pull request #1
Opened 2023-12-07 16:31 UTC by AndrzejSterniewski

Made FeatureBox links (<a>).
Add Hover to FeatureBox.
Remove class 'active' from first FeatureBox.

2023-12-10 10:49 UTC, poldave111 approved these changes

2023-12-10 10:51 UTC, dave8git approved these changes

2023-12-11 08:07 UTC, matwjablonski requested changes
wygląda ok, tylko popraw ten link

2023-12-11 09:19 UTC, AndrzejSterniewski commented on src/components/common/FeatureBox/FeatureBox.js
> +  <a href='#'>
Tagi a zastąpiłem <Link>. W związku z powyższym dodałem import Link.

2023-12-11 09:46 UTC, matwjablonski commented
pozostaje konflikt do rozwiązania

2023-12-11 12:10 UTC, AndrzejSterniewski commented
Ten konflikt jest w pliku yarn.lock. Wynika zapewne z tego że aplikacja nie chciała się u mnie uruchamiać i uaktualniłem yarn lokalnie. Jak postępować w takich sytuacjach? Akceptować to co ja zrobiłem u siebie lokalnie i wypychać do main? Czy rozstrzygać konflikty na korzyść main z tym zastrzeżeniem że pewnie przy kolejenym zadaniu znowu będę miał błąd w uruchomieniu aplikacji i będę musiał lokalnie znowu to u siebie robić (czyli uaktualniać yarn).

2023-12-11 17:31 UTC, juliachanas commented
Ta ciężarówka nie miała być na sztywno zaznaczona ? :)

2023-12-11 21:41 UTC, AndrzejSterniewski commented
Sam nie wiem, to było wg mnie niejednoznaczne i uznałem że lepiej jeśli żaden element nie będzie miał tego domyślnie ustawionego :)

2023-12-11 22:33 UTC, matwjablonski commented
konflikt musi być rozwiązany

2023-12-12 14:25 UTC, AndrzejSterniewski commented
Powinno już być ok. Proszę o sprawdzenie.

2023-12-12 18:04 UTC, juliachanas submitted a review, later dismissed

2023-12-12 18:55 UTC, peterweglo submitted a review, later dismissed
Funkcjonalnie ok i daje approve. Ja bym usunął podkreślenie z linku:
 "<Link style={{ textDecoration: 'none' }}>"

2023-12-12 19:37 UTC, juliachanas submitted a review, later dismissed
Super!:)

2023-12-12 19:38 UTC, peterweglo submitted a review, later dismissed
Super!

2023-12-12 19:40 UTC, matwjablonski requested changes

2023-12-12 19:40 UTC, matwjablonski commented on package.json
> +    "yarn": "^1.22.21"
po co yarn jest w zależnościach do projektu? nie powinno go tu być, a już na pewno nie jako dependencies

2023-12-12 19:43 UTC, AndrzejSterniewski commented on package.json
> +    "yarn": "^1.22.21"
usunąłem

2023-12-12 19:44 UTC, matwjablonski reviewed
dlaczego yarn.lock został usunięty z projektu?

2023-12-12 19:46 UTC, dave8git approved these changes

2023-12-12 19:49 UTC, AndrzejSterniewski commented
> dlaczego yarn.lock został usunięty z projektu?

z tego co pamiętam ten plik u mnie powodował bardzo dużo konflików, ja go lokalnie uaktualniałem bo aplikacja w tym stanie w jakim była uruchamiana z maina w ogóle nie chciała się uruchamiać i wychodziły błędy.

2023-12-12 20:15 UTC, matwjablonski commented
przeinstaluj projekt i wrzuć nowego yarn.lock'a - ten plik powinien zostać w repo

2023-12-12 20:39 UTC, AndrzejSterniewski commented
Tak uczyniłem. Proszę o sprawdzenie.

2023-12-12 20:43 UTC, peterweglo approved these changes

2023-12-12 21:42 UTC, matwjablonski approved these changes

2023-12-12 21:42 UTC, merged