Completes Wdp231201 14
matwjablonski/wdp-2312-01 pull request #11
Opened 2023-12-09 23:59 UTC by dave8git

2023-12-12 19:43 UTC, matwjablonski commented
konflikty

2023-12-12 20:25 UTC, peterweglo requested changes
To jest task 14? Dla mnie menu nie zachowuje się jak w opisie, dalej się rozsypuje w mniejszych rozdzielczościach.

2023-12-14 17:46 UTC, juliachanas requested changes
dołączam się do uwag Piotra, u mnie też wciąż się nie zachowuje się jak w opisie

2023-12-14 22:12 UTC, matwjablonski requested changes
<img width="814" alt="Zrzut ekranu 2023-12-14 o 23 11 36" src="https://github.com/matwjablonski/wdp-2312-01/assets/20933197/a06c188e-2e9c-46fc-ab2b-51dc52ebe0de">
<img width="478" alt="Zrzut ekranu 2023-12-14 o 23 12 14" src="https://github.com/matwjablonski/wdp-2312-01/assets/20933197/831e4218-4715-4339-8cd4-de0c0ae3084d">

to zdecydowanie jest złe zachowanie i wygląda bardzo słabo

2023-12-14 22:12 UTC, matwjablonski commented on src/components/layout/MenuBar/MenuBar.module.scss
> +        background-color: #ffffff;
kolory bierzemy ze zmiennych

2023-12-14 22:12 UTC, matwjablonski commented on src/components/layout/MenuBar/MenuBar.module.scss
> +
jedna linia przerwy powinna być

2023-12-14 23:15 UTC, dave8git commented on src/components/layout/MenuBar/MenuBar.module.scss
> +
Zrobione. Dzięki :)

2023-12-14 23:18 UTC, dave8git commented on src/components/layout/MenuBar/MenuBar.module.scss
> +        background-color: #ffffff;
Poprawione. Dzięki

2023-12-15 10:27 UTC, peterweglo requested changes
Na telefonach, wyszukiwarka wyjeżdza za ekran. Może daj "select category" i "search products" pod siebie a nie obok na telefonach.

2023-12-15 20:44 UTC, peterweglo requested changes
Tak jak pisałem, na telefon lepiej jak "select a category" i "search products" będą w kolumnie pod sobą.
Przy szerokości ok 320px rozjeżdza się nadal nie mówiąc o 280px (Galaxy Fold)
![Zrzut ekranu 2023-12-15 214141](https://github.com/matwjablonski/wdp-2312-01/assets/140804401/4376fd21-90a1-4e27-8d77-62c54d724492)

2023-12-17 12:48 UTC, peterweglo requested changes
Przy ok 500px napis "blog" ci wyjeżdza za ekran".
[
![Zrzut ekranu 2023-12-17 134642](https://github.com/matwjablonski/wdp-2312-01/assets/140804401/a1d01518-721e-41a2-8c8b-dfa123178690)

2023-12-17 19:07 UTC, juliachanas commented
![obraz](https://github.com/matwjablonski/wdp-2312-01/assets/140825579/56de9032-7c25-4910-a774-e8bfcb300937)

tu się coś podziało z tym zaznaczeniem, pierwotnie nie było odstępu, 

i myślę, że przy szerokości ok. 360 dobrze byłoby poszerzyć pola albo trochę wyśrodkować ?

![obraz](https://github.com/matwjablonski/wdp-2312-01/assets/140825579/de7a8256-2db1-401c-ac72-c85af505b9e0)

2023-12-17 19:10 UTC, juliachanas commented on src/components/features/ProductSelect/ProductSelect.module.scss
> +      }
tutaj też wciąż zmienne $orange, których nie należy używać

2023-12-18 12:35 UTC, dave8git commented on src/components/features/ProductSelect/ProductSelect.module.scss
> +      }
zmienione

2023-12-18 13:50 UTC, peterweglo requested changes
Jeszcze w rozdzielczości > 992px do ok 1030px wychodzi przycisk 'blog' poza ekran

![image](https://github.com/matwjablonski/wdp-2312-01/assets/140804401/48412877-417d-47b0-afb0-e0eb7749d4c3)

2023-12-18 16:38 UTC, juliachanas commented on src/components/layout/MenuBar/MenuBar.module.scss
>        font-weight: 500;
tutaj jeszcze masz zmienną $white i w 98 linii też

2023-12-18 17:25 UTC, dave8git commented on src/components/layout/MenuBar/MenuBar.module.scss
>        font-weight: 500;
poprawione

2023-12-18 17:35 UTC, juliachanas commented on src/components/layout/MenuBar/MenuBar.module.scss
> +
Dawidzie.. jeszcze te puste linie, jedna powinna być :) w kilku miejscach w kodzie tak masz

2023-12-18 17:56 UTC, peterweglo submitted a review, later dismissed
Jest ok

2023-12-18 18:53 UTC, AndrzejSterniewski submitted a review, later dismissed
Ok

2023-12-18 19:04 UTC, dave8git commented on src/components/layout/MenuBar/MenuBar.module.scss
> +
Usunięte. Reszta chcę, żeby pozostała dla przejrzystości.

2023-12-18 19:06 UTC, peterweglo approved these changes

2023-12-18 19:09 UTC, juliachanas approved these changes

2023-12-18 19:58 UTC, AndrzejSterniewski approved these changes

2023-12-18 20:57 UTC, merged