Wdp231201 17
matwjablonski/wdp-2312-01 pull request #13
Opened 2023-12-10 09:32 UTC by dave8git

2023-12-11 19:10 UTC, juliachanas commented
Good job! :)

Drobne spostrzeżenie
Na niektórych szerokościach ekranu karty produktów mają różne wysokości - nie widzę na to innego taska, więc może dobrze byłoby to ująć w tym:)

![Zrzut ekranu 2023-12-11 200342](https://github.com/matwjablonski/wdp-2312-01/assets/140825579/3e90ac9e-ede8-4311-b40c-564a9da4fd04)

2023-12-12 20:45 UTC, peterweglo requested changes
Ode mnie taka sama uwaga jak od Julii. Wysokości ProduxBox się sypią i nie są równe w innych rozdzielczościach.

2023-12-17 19:14 UTC, juliachanas commented on src/components/layout/MenuBar/MenuBar.module.scss
> +    background-color: #ffffff;
używamy zmiennych koloróz settings, a jeśli ich nie ma to wprowadzamy nowe i ich używamy :)

2023-12-17 19:18 UTC, juliachanas requested changes
wciąż przy szerokościach 770 do 990 są różne wysokości boxów

2023-12-17 21:01 UTC, peterweglo commented
> wciąż przy szerokościach 770 do 990 są różne wysokości boxów

Może zmień na 3 produkty w tych rozdzielczościach. Produkty rozjeżdżają się bo przyciski  nie mieszczą się w tych produktach z przeceną.

2023-12-21 08:06 UTC, AndrzejSterniewski commented on src/components/features/ProductSearch/ProductSearch.js
> -      </ul>
task nie dotyczył tej sekcji

2023-12-21 08:06 UTC, dave8git reviewed
poprawione

2023-12-21 08:06 UTC, AndrzejSterniewski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> -    align-items: center;
j.w. ta sekcja już została zmergowana

2023-12-21 08:08 UTC, dave8git commented on src/components/features/ProductSearch/ProductSearch.module.scss
> -    align-items: center;
Rozumiem, ale to nie przeszkadza, żeby zmergować. Zmiany zostaną nadpisane.

2023-12-21 08:09 UTC, dave8git commented on src/components/features/ProductSearch/ProductSearch.js
> -      </ul>
Tutaj, to samo, powstały konflikty i stąd napisany kod.

2023-12-21 08:09 UTC, AndrzejSterniewski commented on src/components/layout/MenuBar/MenuBar.module.scss
> -
tutaj podobnie, w jakim celu zmiany w komponencie MenuBar?

2023-12-21 09:23 UTC, AndrzejSterniewski approved these changes
Elementy układają się zgodnie z wymogami zadania.
Element NewFurniture Panel Bar rozjeżdża się na mniejszych ekranach ale przypuszczam ze na ostylowanie tego elementu jest inne zadanie. To o tym nie mówiło.
Approve.

2023-12-21 10:21 UTC, peterweglo approved these changes

2023-12-21 15:49 UTC, juliachanas approved these changes

2023-12-21 22:16 UTC, merged