Completes Wdp231201 18
matwjablonski/wdp-2312-01 pull request #14
Opened 2023-12-10 12:22 UTC by dave8git

2023-12-16 14:40 UTC, peterweglo requested changes
Do szerokości 320px jest ok. Jeśli miałoby być idealnie to na 280px wypadałoby zwiększyć wysokość najniższej stopki bo napis Reserved wychodzi pod. 
Żeby zmergować musisz mieć  zmergowane poprzednie zadania bo tu dużo kodu z innych zadań.

2023-12-16 14:40 UTC, peterweglo commented on src/components/layout/Footer/Footer.js
> +            {' '}
Do usunięcia takie puste elementy.

2023-12-21 11:08 UTC, dave8git commented on src/components/layout/Footer/Footer.js
> +            {' '}
Puste elementy usunięte. Dzięki! :)

2023-12-22 08:15 UTC, peterweglo approved these changes
Teraz jest ok

2023-12-22 09:24 UTC, juliachanas approved these changes

2023-12-22 09:29 UTC, merged