WDP231201-13
matwjablonski/wdp-2312-01 pull request #15
Opened 2023-12-10 14:26 UTC by juliachanas

2023-12-14 18:59 UTC, poldave111 approved these changes

2023-12-14 20:13 UTC, AndrzejSterniewski submitted a review, later dismissed

2023-12-16 13:17 UTC, peterweglo requested changes
Konflikty do rozwiązania.
Po za tym jest ok, działa jak należy.

2023-12-16 20:38 UTC, peterweglo submitted a review, later dismissed

2023-12-16 21:03 UTC, peterweglo submitted a review, later dismissed

2023-12-19 16:00 UTC, matwjablonski requested changes
1) yarn.lock to przywrócenia

2) co to za komponent `functionality`?

2023-12-21 11:59 UTC, AndrzejSterniewski approved these changes
Zadanie wykonane zgodnie z poleceniem. Swipe działa jak powinien.

2023-12-21 22:21 UTC, matwjablonski requested changes
nazwa katalogu komponentu Swipeable powinna być z dużej litery

yarn.lock nadal zmieniony niepotrzebnie

2023-12-27 10:38 UTC, peterweglo approved these changes

2023-12-27 12:24 UTC, AndrzejSterniewski approved these changes

2023-12-27 17:19 UTC, matwjablonski approved these changes

2023-12-27 17:23 UTC, merged