Completes task Wdp231201 20
matwjablonski/wdp-2312-01 pull request #18
Opened 2023-12-10 19:15 UTC by dave8git

2023-12-17 20:18 UTC, peterweglo requested changes
Nie widzę tutaj ani jednej linijki kodu dotyczącej tego zadania....

2023-12-27 11:45 UTC, juliachanas requested changes
sporo kodu, który nie dotyczy zadania.

2023-12-27 13:14 UTC, poldave111 commented
> sporo kodu, który nie dotyczy zadania.

W jaki sposób to zmienić? Nie dołączałem, żadnego zbędnego kodu, tylko robił commity i musiałem zlikwidować konflikty.

2023-12-27 13:17 UTC, dave8git commented
> sporo kodu, który nie dotyczy zadania.

W jaki sposób to zmienić? Nie dołączałem, żadnego zbędnego kodu, tylko robił commity i musiałem zlikwidować konflikty.

2023-12-27 15:05 UTC, peterweglo commented
> > sporo kodu, który nie dotyczy zadania.
> 
> W jaki sposób to zmienić? Nie dołączałem, żadnego zbędnego kodu, tylko robił commity i musiałem zlikwidować konflikty.

Zmerguj swojego brancha z mainem tak żeby został tylko kod z Twojego zadania.

2023-12-29 11:08 UTC, closed without merging