Task WDP231201-1
matwjablonski/wdp-2312-01 pull request #2
Opened 2023-12-07 19:36 UTC by peterweglo

Add images to ProductBox component

2023-12-10 10:52 UTC, dave8git submitted a review, later dismissed

2023-12-10 12:49 UTC, juliachanas submitted a review, later dismissed

2023-12-11 09:45 UTC, matwjablonski requested changes

2023-12-11 09:45 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.module.scss
> +      size: cover;
powyżej masz tez size: contain - wykluczają się, jedno nadpisuje drugie

2023-12-11 17:37 UTC, juliachanas approved these changes

2023-12-11 22:38 UTC, matwjablonski approved these changes

2023-12-11 22:38 UTC, merged