WDP231201-2
matwjablonski/wdp-2312-01 pull request #20
Opened 2023-12-12 21:40 UTC by AndrzejSterniewski

Problem: when displaying numbers greater than 123, element (Counter) behaves incorrectly.
Fix: element behaves correctly when displaying numbers from range 0 - 99999.

Im not sure if this solution is good, I'm open to suggestions.

https://projects.kodilla.com/browse/WDP231201-2

2023-12-12 21:47 UTC, matwjablonski approved these changes

2023-12-12 21:47 UTC, matwjablonski requested changes
<img width="146" alt="Zrzut ekranu 2023-12-12 o 22 47 26" src="https://github.com/matwjablonski/wdp-2312-01/assets/20933197/0de196be-e112-4e72-a24d-c215a96524ad">

zdecydowanie za blisko jest 1

2023-12-13 13:05 UTC, peterweglo reviewed
Ja bym tę odległość od ikony zwiększył rightem np:
right: -10%;

2023-12-13 13:06 UTC, AndrzejSterniewski commented
Zmieniłem padding ale to nie rozwiązuje problemu przy większych liczbach. Zaszwe jakaś liczba będzie "przycięta" (z lewej lub prawej strony). Dodatkowo lokalnie - nic nie zmieniałem - ale przy komendzie yarn start mam błąd i aplikacja się nie uruchamia.
Czy zrobić yarn install? czy może zrobić pulla z maina?

![Zrzut ekranu 2023-12-13 140359](https://github.com/matwjablonski/wdp-2312-01/assets/41449430/d6a918d6-3f51-461c-adbe-23a9970117a0)

2023-12-13 13:09 UTC, peterweglo commented
Ja bym tę odległość od ikony zwiększył rightem np:
right: -10%;

Skopiuj pliki konfiguracyjne z maina, wywal node_modules i potem yarn install

2023-12-13 13:30 UTC, peterweglo commented
A już wiem o co Ci chodzi. Załatw to zmienną jakąś. I tak do koszyka potem będzie wrzucana jakaś wartość z zewnątrz. 

const CompanyClaim = () => {
    const cartCounter = 1277345;  
  return (
.
.
.
 <div className={styles.cartCounter}>
                {cartCounter.toString().slice(0, 5)}
              </div>
.
.
.
  );
};

2023-12-13 13:39 UTC, AndrzejSterniewski commented
Tak to właśnie o to chodziło - o widoczność liczby wewnątrz elementu :)

2023-12-13 16:31 UTC, AndrzejSterniewski commented
Dziękuję za pomoc. Kod poprawiony. Proszę o sprawdzenie.

2023-12-13 18:04 UTC, peterweglo submitted a review, later dismissed
Jest ok.

2023-12-13 22:36 UTC, matwjablonski requested changes

2023-12-13 22:36 UTC, matwjablonski commented on src/components/layout/CompanyClaim/CompanyClaim.module.scss
> +        right: -20%;
to nie jest dobry pomysł, na mniejszych ekranach elementy wejdą za krawędź ekranu - lepiej dodać to w ten sposób żeby zachować 0 po prawej stronie

2023-12-14 11:16 UTC, AndrzejSterniewski commented on src/components/layout/CompanyClaim/CompanyClaim.module.scss
> +        right: -20%;
Tak, zauważyłem to, zmodyfikowałem na -10% (wtedy pole z liczbą nie wchodzi na ikonę koszyka). Natomiast jest inne zadanie dotyczące RWD tej sekcji (WDP231201-15) i nad tym zadaniem aktualnie się męczę.
Przy ustawionym 0 pole z liczbą nachodzi na koszyk.

2023-12-14 22:22 UTC, peterweglo approved these changes
Dla mnie jeat ok jesli rwd jest w innym tasku.

2023-12-17 19:36 UTC, juliachanas approved these changes

2023-12-18 11:37 UTC, merged