Completes task Wdp231201 25
matwjablonski/wdp-2312-01 pull request #21
Opened 2023-12-13 16:34 UTC by dave8git

2023-12-18 10:06 UTC, peterweglo requested changes
W banerze prawym górnym zwiększył bym padding dolny napisu "collection"
W banerze prawym dolnym według zadania powinno być zdjęcie po lewej i baner z napisem po prawej. U Ciebie jest zdjęcie na całą szerokość z napisem w tle.

Dużo kodu do zmergowania z poprzednich zadań.

Poza tym sama sekcja promocje i jej kod wygląda ok.

2023-12-18 10:08 UTC, peterweglo requested changes

2023-12-18 10:08 UTC, peterweglo commented on src/components/layout/Promo/Promo.module.scss
> +    color: $primary;
Zmienna z kolorem do zmiany

2023-12-18 10:08 UTC, peterweglo commented on src/redux/initialState.js
> +
Nie lepiej wrzucić zdjęcia do folderu public niż korzystać z linków?

2023-12-28 08:08 UTC, dave8git commented on src/redux/initialState.js
> +
Wolałbym zostawić linki, tak jest bardziej dynamicznie, w przypadku tworzenia jakiegoś panelu admin, łatwiej wkleić linki niż uploadować zdjęcie (w zależności od miejsca na serverze).

2023-12-28 08:16 UTC, dave8git commented on src/components/layout/Promo/Promo.module.scss
> +    color: $primary;
Zmienione.

2023-12-28 15:21 UTC, peterweglo requested changes
Teraz wygląda ok. Do usunięcia kod z zadania WDP231201_20.

2023-12-29 11:09 UTC, closed without merging