WDP231201-15
matwjablonski/wdp-2312-01 pull request #23
Opened 2023-12-14 16:47 UTC by AndrzejSterniewski

Remove text "login" and "register" next to icons on smaller screens.
Changed position of elements in banner. CompanyClaim.

2023-12-16 13:50 UTC, peterweglo requested changes
Na telefonach wygląd się dalej sypie. Może daj liczbę z koszyka pod albo nad koszyk na środku a nie z prawej strony w mniejszych rozdzielczościach, chyba będzie łatwiej zrobić RWD.

2023-12-20 20:07 UTC, AndrzejSterniewski commented
O jakiej rozdzielczości mówisz? Mentor pisał że aplikacja musi obsłużyć szerokości od 320px do 1920px. Jak ja patrzę to na 320px jest spoko.

2023-12-21 09:10 UTC, dave8git approved these changes

2023-12-22 09:42 UTC, peterweglo commented
> O jakiej rozdzielczości mówisz? Mentor pisał że aplikacja musi obsłużyć szerokości od 320px do 1920px. Jak ja patrzę to na 320px jest spoko.

Jak było 5cyfr w koszyku to wydaję mi się że wychodziły za ekran, ale teraz widzę, że jest ok.

2023-12-22 09:43 UTC, peterweglo approved these changes

2023-12-27 10:18 UTC, matwjablonski approved these changes

2023-12-27 10:18 UTC, merged