WDP231201-31
matwjablonski/wdp-2312-01 pull request #30
Opened 2023-12-17 19:27 UTC by peterweglo

Add functionality to Brands component

2023-12-29 12:09 UTC, dave8git approved these changes

2023-12-29 21:59 UTC, matwjablonski requested changes

2023-12-29 21:59 UTC, matwjablonski commented on src/components/features/Brands/Brands.js
> +    if (window.innerWidth < 415) {
415, 768, 992 - MagicNumbers

dogadaj się z Dawidem, w jednym PR wskazałem że mógłby zrobić z tych wartości jakieś globalne stałe i wówczas można byłoby je wykorzystywać

2023-12-30 12:09 UTC, peterweglo commented on src/components/features/Brands/Brands.js
> +    if (window.innerWidth < 415) {
Poprawione :)

2023-12-30 12:13 UTC, juliachanas approved these changes
ok

2023-12-30 15:50 UTC, dave8git approved these changes

2024-01-01 23:11 UTC, matwjablonski approved these changes

2024-01-01 23:11 UTC, merged