Add srcszRedux file
matwjablonski/wdp-2312-01 pull request #32
Opened 2023-12-27 19:17 UTC by dave8git

2023-12-28 15:14 UTC, peterweglo requested changes
To chyba powinno tak działać, że w zależności od szerokości wyświetla się różna ilość elementów na stronie. Na razie zawsze się wyświetla 8 elementów w NewFurniture. Dla tabletów jak mieszczą się 3 elementy w rzędzie to tylko 3szt powinny się ogólnie wyświetlać na stronie. Jak 2 to 2. Ja tak rozumiem to zadanie.

2023-12-28 21:04 UTC, peterweglo approved these changes

2023-12-28 21:11 UTC, peterweglo requested changes
Wyświetla się teraz dobra ilość ale powinna się zwiększyć ilość podstron (kropek) gdy jest mniej elementów na stronie tak żeby dało się wszystkie produkty przejrzeć.

2023-12-29 09:51 UTC, dave8git commented
Ok, dzięki. Poprawione. Wyświetla się teraz właściwa liczba kropek.

2023-12-29 12:11 UTC, closed without merging