WDP231201-32
matwjablonski/wdp-2312-01 pull request #35
Opened 2023-12-28 14:52 UTC by peterweglo

Add swipe to Brands component

2023-12-31 15:55 UTC, dave8git submitted a review, later dismissed

2024-01-01 19:18 UTC, juliachanas requested changes
jest oki :) tylko do usunięcia kod z zadania 31 ( m.in. plik ze stałymi, initialstate)

2024-01-02 10:04 UTC, peterweglo commented
> jest oki :) tylko do usunięcia kod z zadania 31 ( m.in. plik ze stałymi, initialstate)

Poprawione :)

2024-01-02 13:58 UTC, matwjablonski approved these changes

2024-01-02 13:58 UTC, merged

2024-01-02 13:58 UTC, AndrzejSterniewski approved these changes
Działa jak powinno :)