Wdp231201 20 fix
matwjablonski/wdp-2312-01 pull request #37
Opened 2023-12-29 10:21 UTC by dave8git

2023-12-29 11:04 UTC, peterweglo approved these changes
Teraz jest ok. 
RWD menu NewFurniture jeszcze do zrobienia, ale tego nie było w tym tasku.

2023-12-29 12:06 UTC, peterweglo submitted a review, later dismissed

2023-12-29 12:19 UTC, matwjablonski requested changes

2023-12-29 12:19 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.js
> +  let classRWD = screen.viewport === 'desktop' ? 'col-lg-3' : (screen.viewport === 'tablet' ? 'col-md-4' : 'col-sm-6');
dlaczego to jest `let`? zmieniasz to gdzieś?

2023-12-29 12:19 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.js
> +  let classRWD = screen.viewport === 'desktop' ? 'col-lg-3' : (screen.viewport === 'tablet' ? 'col-md-4' : 'col-sm-6');
druga uwaga ten ternary if jest nieczytelny, przerób to na funkcję

2023-12-29 12:19 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.js
> +            {categoryProducts.slice(activePage * screen.elements, (activePage + 1) * screen.elements).map(item => (
wynieś logikę przed returna, tutaj powinno zozstać tylko mapowanie

2023-12-29 12:19 UTC, matwjablonski commented on src/components/layout/MainLayout/MainLayout.js
> +  const rwd = () => {
nazwa funkcji mało mówi - wg mnie powinna nazywać się jakoś w stylu:

`setResponsiveView`

2023-12-29 12:19 UTC, matwjablonski commented on src/components/layout/MainLayout/MainLayout.js
> +    if (visualViewport.width > 992) {
992, 768, 576 to takie MagicNumbers, przenieś je do zmiennych gdzieś globalnie i zaimportuj stamtąd

2023-12-29 12:19 UTC, matwjablonski commented on src/components/layout/MainLayout/MainLayout.js
> +  const [elements, setElements] = useState('');
patrząc na logikę lepszą nazwą byłoby `setNumberOfElements` - ponadto w dalszej części kodu przypisujesz liczby do tego stanu, a tutaj jako wartość domyślną dajesz pusty string - tak to zostać nie może

2023-12-29 12:19 UTC, matwjablonski commented on src/components/layout/MainLayout/MainLayout.js
> +  });
na pewno ten useEffect ma się wykonywać przy każdym re-renderze? o wiele sensowniej byłoby dać tablicę zależności na zmienne stanu

2023-12-29 12:19 UTC, matwjablonski commented on src/components/layout/MainLayout/MainLayout.js
> +    dispatch(setScr({ viewport, elements }));
zapisujesz do reduxa viewport i ilość elementów, ale nie pobierasz ich stamtąd tylko ze stanu komponentu - dlaczego?

2023-12-30 15:58 UTC, dave8git commented on src/components/layout/MainLayout/MainLayout.js
> +  });
Jedną zmienną czy tablicę, z viewport i elements?

2023-12-30 16:04 UTC, dave8git commented on src/components/features/NewFurniture/NewFurniture.js
> +            {categoryProducts.slice(activePage * screen.elements, (activePage + 1) * screen.elements).map(item => (
Ja tylko tą logikę zmieniłem (dodałem screen.elements), była tu prawdopodobnie od początku projektu...

2023-12-31 00:41 UTC, dave8git commented on src/components/layout/MainLayout/MainLayout.js
> +    dispatch(setScr({ viewport, elements }));
Zrobione.

2023-12-31 00:41 UTC, dave8git commented on src/components/layout/MainLayout/MainLayout.js
> +  const [elements, setElements] = useState('');
zrobione.

2023-12-31 00:42 UTC, dave8git commented on src/components/layout/MainLayout/MainLayout.js
> +  const [elements, setElements] = useState('');
Poprawiłem, stan korzysta ze stanu reduxa.

2023-12-31 00:46 UTC, dave8git commented on src/components/layout/MainLayout/MainLayout.js
> +  });
Zrobione.

2023-12-31 13:50 UTC, AndrzejSterniewski approved these changes
Zadanie wykonane. Approve.

2023-12-31 14:23 UTC, peterweglo approved these changes

2024-01-01 23:07 UTC, merged