Task-10
matwjablonski/wdp-2312-01 pull request #7
Opened 2023-12-09 14:17 UTC by AndrzejSterniewski

Add dropdown menu on categories. 
Menu made in html and in css in ProductSearch.js and ProductSearch.module.scss files.

2023-12-10 10:58 UTC, dave8git submitted a review, later dismissed
Super, select na razie na sztywno, ale pewnie będzie jakiś task gdzie dodamy jakiegoś map-a ze stanu :)

2023-12-13 12:26 UTC, AndrzejSterniewski commented
Nie wiem skąd błędy w deploy preview oraz all checks have failed. U mnie lokalnie aplikacja się uruchamia. Proszę o pomoc,

2023-12-15 09:02 UTC, peterweglo commented
> Nie wiem skąd błędy w deploy preview oraz all checks have failed. U mnie lokalnie aplikacja się uruchamia. Proszę o pomoc,

Masz zmieniony plik yarn.lock.
Skopiuj go z maina i powinno być ok.

2023-12-15 09:20 UTC, peterweglo reviewed
Co do kodu, to jeśli ma być lista w liście to ul powinien być osobnym < li ></ li > według mnie.

2023-12-15 10:05 UTC, AndrzejSterniewski commented
Faktycznie trochę przeorganizowałem strukturę na wydaje mi się że zgodną z poleceniem (ul>li>ul>li). Dziękuję za podpowiedź i uwagi.

2023-12-15 10:29 UTC, peterweglo approved these changes
Teraz jest ok.

2023-12-15 10:34 UTC, peterweglo requested changes
Teraz jest ok

2023-12-15 10:42 UTC, peterweglo approved these changes
Teraz jest ok.

2023-12-17 18:41 UTC, juliachanas approved these changes

2023-12-18 11:41 UTC, matwjablonski requested changes
zadanie nie polegało na podbijaniu wersji, wiec lock nie powinien się zmienić. przywróć go proszę do stanu z brancha głównego

2023-12-18 11:41 UTC, matwjablonski commented on src/components/layout/CompanyClaim/CompanyClaim.js
> +            <div className={styles.cartCounter}>12345678</div>
dlaczego to jest w tym PR?

2023-12-18 11:41 UTC, matwjablonski commented on src/components/layout/CompanyClaim/CompanyClaim.module.scss
> +        min-width: 28px;
jw

2023-12-18 14:14 UTC, AndrzejSterniewski commented on src/components/layout/CompanyClaim/CompanyClaim.module.scss
> +        min-width: 28px;
Poprawiłem. Sprawdź proszę czy o to chodziło.

2023-12-18 16:56 UTC, AndrzejSterniewski commented on src/components/layout/CompanyClaim/CompanyClaim.module.scss
> +        min-width: 28px;
Nie wiem czy jest poprawnie. Robiłem git pull origin main oraz cofałem zmiany. Czy to taką wersję chodzi?

2023-12-18 17:03 UTC, juliachanas commented on src/components/layout/CompanyClaim/CompanyClaim.js
> +const cartCounter = 0;
tutaj masz nieużywaną stałą, może warto ją usunąć ?

2023-12-18 17:18 UTC, AndrzejSterniewski commented on src/components/layout/CompanyClaim/CompanyClaim.js
> +const cartCounter = 0;
słuszna uwaga ale miałem wrócić do stanu z brancha main więc tego się póki co trzymałem, ta stała dotyczy innego taska

2023-12-18 19:34 UTC, peterweglo submitted a review, later dismissed
Teraz jest ok. Można by dodać jeszcze cursor: pointer i jakieś hovery na te kategorie w liście, ale chyba to zadanie tego nie dotyczy.

2023-12-18 19:44 UTC, AndrzejSterniewski commented
Zgadza się., to kwestia kosmetyczna do dopieszczenia w przyszłości. Zadanie o tym nie mówiło więc wysyłam rozwiązanie w tej wersji.

2023-12-18 19:45 UTC, juliachanas submitted a review, later dismissed
ok:)

2023-12-19 07:58 UTC, peterweglo reviewed
Konflikty do usunięcia

2023-12-19 12:33 UTC, peterweglo requested changes

2023-12-19 12:33 UTC, peterweglo commented on src/components/features/ProductSelect/ProductSelect.js
> +export default ProductSelect;
Do usunięcia kod z innych tasków.

2023-12-19 12:33 UTC, peterweglo commented on src/components/features/ProductSelect/ProductSelect.module.scss
> +    }
Do usunięcia kod z innych tasków.

2023-12-19 12:33 UTC, peterweglo commented on src/components/layout/MenuBar/MenuBar.js
Do usunięcia kod z innych tasków.

2023-12-19 12:33 UTC, peterweglo commented on src/components/layout/MenuBar/MenuBar.js
>              </div>
Do usunięcia kod z innych tasków.

2023-12-19 12:47 UTC, peterweglo reviewed
Powinny tylko zostać zmiany w ProductSearch

2023-12-19 12:55 UTC, AndrzejSterniewski commented on src/components/features/ProductSelect/ProductSelect.js
> +export default ProductSelect;
chodzi Ci o całkowite usunięcie komponentu ProductSelect?

2023-12-19 13:03 UTC, dave8git submitted a review, later dismissed

2023-12-19 13:09 UTC, peterweglo commented on src/components/features/ProductSelect/ProductSelect.js
> +export default ProductSelect;
Nie, chodzi o to że nie powinno tu być żadnych zmian widocznych poza Twoim zadaniem. Powinieneś mieć tylko zmiany w plikach ProductSearch a w pozostałych powinien być stricte kod z maina.

2023-12-19 13:54 UTC, peterweglo approved these changes
Jest ok

2023-12-19 15:48 UTC, AndrzejSterniewski commented
Jeszcze spróbuję poprawić położenie rozwijanego menu bo u mnie na podglądzie jego położenie zmienia się w zależności od rozmiaru ekranu.

2023-12-19 16:48 UTC, AndrzejSterniewski commented on src/components/features/ProductSelect/ProductSelect.js
> +export default ProductSelect;
Sprawdź Dawid, powinno już być dobrze.

2023-12-19 16:57 UTC, dave8git approved these changes

2023-12-19 17:00 UTC, dave8git commented on src/components/features/ProductSelect/ProductSelect.js
> +export default ProductSelect;
Jest super! Mój approve juz jest.

2023-12-19 17:32 UTC, juliachanas approved these changes

2023-12-19 17:59 UTC, peterweglo approved these changes

2023-12-20 13:44 UTC, matwjablonski approved these changes

2023-12-20 13:44 UTC, merged